### ISSUE TITLE
Index out a few seconds after launching any mylg command

### ISSUE THREAD

**Issue by lahwran** [mehrdadrad/mylg#80]
```
lahwran@lahwran:~$ mylg trace us7.wormax.io
trace route to us7.wormax.io (144.217.254.199), 30 hops max
1  192.168.1.2 6.783 ms 1.418 ms 4.268 ms
2  192.168.0.1 1.387 ms 1.389 ms 1.312 ms
3  96.120.88.121 [ASN 7922/COMCAST-7922] 11.204 ms 10.470 ms 11.854 ms
4  be-10001-sur03.pinole.ca.sfba.comcast.net. (68.85.100.77) [ASN 7922/COMCAST-7922] 12.258 ms 11.932 ms 14.548 ms
5  be-224-rar01.pinole.ca.sfba.comcast.net. (162.151.78.185) [ASN 7922/COMCAST-7922] 12.167 ms 13.476 ms 12.566 ms
6  hu-0-1-0-3-ar01.santaclara.ca.sfba.comcast.net. (68.85.154.45) [ASN 7922/COMCAST-7922] 76.399 ms 15.721 ms 15.345 ms
7  be-33651-cr02.sunnyvale.ca.ibone.comcast.net. (68.86.90.93) [ASN 7922/COMCAST-7922] 307.349 ms 17.319 ms 18.846 ms
8  be-11021-cr02.1601milehigh.co.ibone.comcast.net. (68.86.86.66) [ASN 7922/COMCAST-7922] 41.864 ms 45.102 ms 41.049 ms
9  be-11721-cr02.denver.co.ibone.comcast.net. (68.86.86.77) [ASN 7922/COMCAST-7922] 43.513 ms 38.890 ms 46.868 ms
10 be-10517-cr02.350ecermak.il.ibone.comcast.net. (68.86.85.169) [ASN 7922/COMCAST-7922] 70.580 ms 65.817 ms 66.156 ms
panic: runtime error: index out of range

goroutine 10 [running]:
panic(0x4516280, 0xc4200100e0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mehrdadrad/mylg/ns.fetchNSHosts(0x0, 0x0, 0x0)
        /Users/mehrdad/golang/src/github.com/mehrdadrad/mylg/ns/ns.go:357 +0x98d
github.com/mehrdadrad/mylg/ns.(*Request).Init(0xc42010c460)
        /Users/mehrdad/golang/src/github.com/mehrdadrad/mylg/ns/ns.go:99 +0x7f
created by main.init.1
        /Users/mehrdad/golang/src/github.com/mehrdadrad/myLG/mylg.go:104 +0x125
```

**Comment by lahwran** [comment]
update: it happens without actually doing anything. this is using the latest mac version on the site as of sep 30 at 9:10 pm.

```
lahwran@lahwran:~$ mylg

=================================================
                          _    ___
                _ __ _  _| |  / __|
               | '  \ || | |_| (_ |
               |_|_|_\_, |____\___|
                      |__/

                 My Looking Glass
           Free Network Diagnostic Tool
                  http://mylg.io
================== myLG v0.2.6 ==================
local> trace

    usage:
          trace IP address / domain name [options]
    options:
          -r             Real-time response time at each point along the way
          -n             Do not try to map IP addresses to host names
          -nr            Do not try to map IP addresses to ASN,Holder (RIPE NCC)
          -m MAX_TTL     Set the maximum number of hops
          -4             Forces the trace command to use IPv4 (target should be hostname)
          -6             Forces the trace command to use IPv6 (target should be hostname)
          -T             Set the real-time terminal theme (dark|light)
          -c             Set the number of pings sent
          -p             Set the packet size in bytes inclusive headers (default 52 bytes)
          -u             Use UDP datagram instead of ICMP
    Example:
          trace 8.8.8.8
          trace freebsd.org -r

local> panic: runtime error: index out of range

goroutine 34 [running]:
panic(0x4516280, 0xc42000c0f0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mehrdadrad/mylg/ns.fetchNSHosts(0x0, 0x0, 0x0)
        /Users/mehrdad/golang/src/github.com/mehrdadrad/mylg/ns/ns.go:357 +0x98d
github.com/mehrdadrad/mylg/ns.(*Request).Init(0xc42010c460)
        /Users/mehrdad/golang/src/github.com/mehrdadrad/mylg/ns/ns.go:99 +0x7f
created by main.init.1
        /Users/mehrdad/golang/src/github.com/mehrdadrad/myLG/mylg.go:104 +0x125
lahwran@lahwran:~$
```

**Comment by lahwran** [comment]
```
lahwran@lahwran:~$ mylg

=================================================
                          _    ___
                _ __ _  _| |  / __|
               | '  \ || | |_| (_ |
               |_|_|_\_, |____\___|
                      |__/

                 My Looking Glass
           Free Network Diagnostic Tool
                  http://mylg.io
================== myLG v0.2.6 ==================
local> panic: runtime error: index out of range

goroutine 34 [running]:
panic(0x4516280, 0xc42000c0f0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mehrdadrad/mylg/ns.fetchNSHosts(0x0, 0x0, 0x0)
        /Users/mehrdad/golang/src/github.com/mehrdadrad/mylg/ns/ns.go:357 +0x98d
github.com/mehrdadrad/mylg/ns.(*Request).Init(0xc42010c460)
        /Users/mehrdad/golang/src/github.com/mehrdadrad/mylg/ns/ns.go:99 +0x7f
created by main.init.1
        /Users/mehrdad/golang/src/github.com/mehrdadrad/myLG/mylg.go:104 +0x125
lahwran@lahwran:~$
```

**Comment by mehrdadrad** [comment]
@lahwran it fixed at repo, also for packages except mac. download mylg-0-2.7 or compile it.

**Comment by manstrocity** [comment]
Problem still persists on Mac, please help.

local> panic: runtime error: index out of range

goroutine 4 [running]:
panic(0x4516280, 0xc42000c0d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mehrdadrad/mylg/ns.fetchNSHosts(0x0, 0x0, 0x0)
	/Users/mehrdad/golang/src/github.com/mehrdadrad/mylg/ns/ns.go:357 +0x98d
github.com/mehrdadrad/mylg/ns.(*Request).Init(0xc4201243f0)
	/Users/mehrdad/golang/src/github.com/mehrdadrad/mylg/ns/ns.go:99 +0x7f
created by main.init.1
	/Users/mehrdad/golang/src/github.com/mehrdadrad/myLG/mylg.go:104 +0x125

**Comment by mehrdadrad** [comment]
@manstrocity can you compile the latest version on your Mac?

**Comment by mehrdadrad** [comment]
@manstrocity I just uploaded the mylg version 0.2.7 for Mac. it's not package so you should follow the below once it downloaded. [http://mylg.io/dl/mac/0.2.7/mylg](http://mylg.io/dl/mac/0.2.7/mylg)
chmod +x ./mylg
cp ./mylg /usr/local/bin/

**Comment by manstrocity** [comment]
Thanks, I just downloaded a file. What kind of file extension is dms? I tried to untar and nothing happened.

**Comment by mehrdadrad** [comment]
@manstrocity it's not package, just a binary file.
try the below at downloaded directory:
chmod +x ./mylg
cp ./mylg /usr/local/bin/
if you have mylg under /usr/bin:
cp ./mylg /usr/bin/

**Comment by manstrocity** [comment]
It works, hoping to get to know this app.  

Only line I would change is:
sudo cp ./mylg /usr/local/bin/
