### ISSUE TITLE
error while waiting for command turns off echo

### ISSUE THREAD

**Issue by nickodell** [mehrdadrad/mylg#9]
### Reproduction instructions

1. Run mylg as unprivileged user.
2. Type 'web'
3. Ping something in the web interface.
4. mylg gives this error: `local> 2016/08/30 13:19:21 listen err, listen ip4:icmp : socket: operation not permitted`

### Result

Terminal stops echoing input until you type `stty echo`

### Expected

mylg should clean up if it exits unexpectedly.

Note: this doesn't happen if you type a command that triggers an error, like `ping` as an unprivileged user.

**Comment by mehrdadrad** [comment]
Thank you for reporting this issue. I just fixed the code and the permission error will be added to web dashboard as well later. please let me know if you see any issue at the next release.

**Comment by nickodell** [comment]
This doesn't quite fix the issue, because now if I run ./mylg as an unprivileged user, it exits immediately, and turns off echo.

```
nick@host:~/gopath/src/mylg$ ./mylg

=================================================	
                          _    ___ 
                _ __ _  _| |  / __|
               | '  \ || | |_| (_ |
               |_|_|_\_, |____\___|
                      |__/          
	
                 My Looking Glass
           Free Network Diagnostic Tool
                  http://mylg.io
================== myLG v0.2.3 ==================
local> 2016/09/03 14:37:12 listen err, listen ip4:icmp : socket: operation not permitted
nick@host:~/gopath/src/mylg$ nick@host:~/gopath/src/mylg$ 
```

I'm guessing that the program exiting while it's waiting for input is the cause of this.

**Comment by mehrdadrad** [comment]
I couldn't duplicate this issue at Ubuntu 14.04 and OS X.
It should be showed just the error as we have error handling for listening to web dashboard TCP port. I keep this open for further investigation.

**Comment by mehrdadrad** [comment]
@nickodell can you check w/ new version (v0.2.4) and let me know? I'd like to know your OS and what's permission your username has.

**Comment by nickodell** [comment]
I don't see a tag for v0.2.4. Did you push it?

Current master 5dc49a does not build for me, failing with this error:

```
nick@host:~/gopath/src/mylg$ go build mylg
# mylg
./mylg.go:234: p.Banner undefined (type *packet.Packet has no field or method Banner)
./mylg.go:287: too many arguments in call to "github.com/mehrdadrad/mylg/icmp".NewTrace
./mylg.go:294: trace.Print undefined (type *"github.com/mehrdadrad/mylg/icmp".Trace has no field or method Print)
```

My user account is in the sudoers group, but otherwise has no special permissions.

OS is Debian Jessie (8.5), 64-bit.

If you need anything else, or any more details, let me know.

**Comment by mehrdadrad** [comment]
@nickodell I haven't tagged yet as I'm fixing minor bugs, tomorrow I'll do
I think you need go get -u github.com/mehrdadrad/mylg

**Comment by nickodell** [comment]
This looks good to me. The bug is fixed on my end.

**Comment by mehrdadrad** [comment]
Thanks!
